### PR TITLE
Refactor RestUserService methods to handle exceptions

### PR DESCRIPTION
**Pull request by thib-rdr**
This pull request refactors the RestUserService methods `findLegacyUser` and `isPasswordValid` to handle exceptions. Previously, these methods would throw a `RestUserProviderException` when a `RuntimeException` or `IOException` occurred. Now, instead of throwing an exception, the methods log the error message and return an empty optional or `false` respectively.

### CODE REVIEW

**Comment by daniel-frak** [comment]
Hello!

Sounds like a good idea.

However, something mysterious is happening with the CI pipeline - it's failing SonarCloud analysis with `Error status returned by url [https://api.sonarcloud.io/analysis/jres?os=linux&arch=x86_64]: 401`.

Other PRs don't seem to have this problem, it seems to be just this one (see [this test PR](https://github.com/daniel-frak/keycloak-user-migration/pull/215) I just made) O_O

I'll try to investigate this, but any help is appreciated if you know why that might be the case.

**Comment by thib-rdr** [comment]
Hey @daniel-frak. Thanks for your answer, I renamed the commit, hoping that will fix the build.

Please do let me know if I can help you in any other way.

**Comment by daniel-frak** [comment]
Sorry for not getting back to you for so long.
I think I know why the pipeline is failing and it's my/Github's fault.

I'll try to find some time to check the PR manually and hopefully merge it in soon :)

**Comment by thib-rdr** [comment]
I just removed the unused imports @daniel-frak 

Thanks again for your help

**Comment by daniel-frak** [comment]
Great, thanks for the contribution!

**Comment by thib-rdr** [comment]
@daniel-frak could you please let me know when you plan to do your next release ? Thanks in advance !

**Pull request merged**
