### PR TITLE
#21 Client roles

### PR DESCRIPTION
**Pull request by clahavya**
#21 Adding support for client roles

### CODE REVIEW

**Comment by daniel-frak** [comment]
Thanks for the contribution!
Sorry for taking so long to look at this PR.

Could you add some unit tests to document the change and so that we can make sure it's all working properly (and so we're back to 100% coverage)?

**Comment by clahavya** [comment]
Is SonarCloud failing due to new test migratesUnmappedClientRoles does not cover when realm.getClients() returns null? This is already covered by the old test migratesUnmappedRoles

**Comment by daniel-frak** [comment]
Indeed, this is curious - I'm not sure why the `for` loop is only partially covered according to SonarCloud.

I won't have time today, sadly, but I'll take a closer look as soon as possible.
Worst comes to worst, I'll just merge your PR and worry about it later, though it would be best to solve this earlier.

Let me know in case you figure this out before I do! :)

**Comment by daniel-frak** [comment]
LGTM, thanks a lot! :)

**Pull request merged**
