### PR TITLE
Fix group migration

### PR DESCRIPTION
**Pull request by niveau0**
I had to fix the search for existing groups, if multiple users of the same group get migrated. 
The groups name was taken as ID for the search, which is not correct, since new groups get a UUID as ID.
So existing groups were never found, but resulted in a duplicate key exception.

Maybe it helps.

### CODE REVIEW

**Comment by daniel-frak** [comment]
Thanks for the fix! Could you add a test reproducing the fixed bug in addition to the code?

It would be cool if you also fixed the two code smells found by SonarQube, but that's totally optional, as they are not your fault at all (they're result of applying more stringent analysis rules recently) :)

**Comment by niveau0** [comment]
@daniel-frak 
Hi, sorry not sure what type of test you think about. The tests already exist (100% coverage), I just had to adapt the test to match the code, since the test was mocking groupById, which is now no longer used now.
So I think its difficult to create a test for the old behaviour which no longer exists.
And the code smells seem to have disappeared?

**Comment by daniel-frak** [comment]
The idea is to write a test which would fail before your fix was implemented, so in this case you should write a test showing explicitly that an existing group will be found.

This would give us a test documenting the change you made in this PR and ensuring that anyone else modifying the `UserModelFactory` class won't accidentally introduce a change undoing the bugfix.

The actual code for the test escapes me at the moment, but the name of the test would probably be something like `assignsUserToExistingGroup`. This might be hard to achieve given that it's just a unit test, but I think it would be a good idea to have a test shielding future maintainers from undoing your fix (i.e. accidentally passing the group name as the group id).

100% coverage is not a good metric on its own, it's just part of the equation. We need to make sure that as many edge cases as possible are tested, especially those which were proven to not work well previously.

**Comment by niveau0** [comment]
@daniel-frak will try my best and add the test, just lacking time currently ;-)

**Comment by daniel-frak** [comment]
Thanks! Take your time, I will review and merge it when it's ready :)

**Comment by ChristianNavolskyi** [comment]
We stumbled over the same issue with migrating users to existing groups and created a pull request to the repo of Heydenwall to add the requested test and also merged the current master into his branch. The [pull request](https://github.com/Heydenwall/keycloak-user-migration/pull/1) is just newly opened and I wanted to let you know of the changes.

**Comment by daniel-frak** [comment]
That's great! Thank you both for the contribution :)

**Pull request merged**
