### PR TITLE
add a release gh action

### PR DESCRIPTION
**Pull request by heddn**
Replaces #26

### CODE REVIEW

**Comment by heddn** [comment]
The following secrets will need to be defined for the CI to function correctly:

          maven-repo-server-username: ${{ secrets.MVN_REPO_PRIVATE_REPO_USER }}
          maven-repo-server-password: ${{ secrets.MVN_REPO_PRIVATE_REPO_PASSWORD }}
          gpg-key-id: ${{ secrets.GPG_KEY_ID }}
          gpg-key: ${{ secrets.GPG_KEY }}

**Comment by heddn** [comment]
I tested this about as far as I can test things without actual access to add GH secrets. https://github.com/heddn/keycloak-user-migration/actions/workflows/release.yml runs until it fails because the secrets do not exist.

**Comment by daniel-frak** [comment]
Thanks for the contribution!
Isn't it a little bit overkill to release this to a central repository, though? I don't think there's a way to automatically import the plugin into Keycloak that way, so it doesn't seem to bring any benefits compared to just releasing on Github.

Additionally, IIRC the main problem with the older MR (#26) was the lack of automatic version incrementing, which also seems to be absent here.

**Comment by heddn** [comment]
> Thanks for the contribution! Isn't it a little bit overkill to release this to a central repository, though? I don't think there's a way to automatically import the plugin into Keycloak that way, so it doesn't seem to bring any benefits compared to just releasing on Github.

Maybe it is overkill, but java works off maven as a dependency system. We could just create a new tag/release on GH directly if that is your preference.
 
> Additionally, IIRC the main problem with the older MR (#26) was the lack of automatic version incrementing, which also seems to be absent here.

I think the older and _this_ PR use the [release plugin](https://maven.apache.org/maven-release/maven-release-plugin/). Which does all the right things to bump the version.

**Comment by daniel-frak** [comment]
I'm closing this due to finally getting around to creating the workflow I wanted.

Thanks to everyone who contributed!

**Pull request closed without merging**
